export enum EventType {
    SHIPWRECK = 'SHIPWRECK',
    MEG_SIGHTING = 'MEG_SIGHTING',
    ASHEN_LORD = 'ASHEN_LORD',
    REAPER_SIGHTING = 'REAPER_SIGHTING',
    ALLIANCE = 'ALLIANCE',
    FORT_OF_FORTUNE = 'FORT_OF_FORTUNE',
    FORT_OF_THE_DAMNED = 'FORT_OF_THE_DAMNED',
    SKELETON_FLEET = 'SKELETON_FLEET',
    GHOST_FLEET = 'GHOST_FLEET',
    TREASURE_MAP = 'TREASURE_MAP',
    MERCHANT_CONTRACT = 'MERCHANT_CONTRACT',
    EMISSARY_FLAG = 'EMISSARY_FLAG',
    OTHER = 'OTHER'
} 