server:
  port: 8080

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: voyagewatch
      auto-index-creation: true
  redis:
    host: localhost
    port: 6379
    database: 0

logging:
  level:
    org.springframework.web: INFO
    com.voyagewatch: DEBUG 